version: '3'
services:
  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
    ports:
      - "8081:8081"
  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    ports:
      - "8082:8082"
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"
    command: ["--reporter.grpc.host-port=jaeger-logzio:14250"] # This is only needed for streaming traces to Logz.io
  
  # You can omit this, if you want to use local jaeger
  jaeger-logzio: 
    image: logzio/jaeger-logzio-collector:latest
    container_name: jaeger-logz
    ports:
      - 14268:14268
      - 14269:14269
      - 14250:14250
    environment:      
      ACCOUNT_TOKEN: <YOUR_TOKEN>
      REGION: "eu"
      GRPC_STORAGE_PLUGIN_LOG_LEVEL: 
  